##
# Game of life
#
# @file
# @version 0.1

antsim-release: ./main.cpp
	g++ -c -O3 -s -ffast-math -std=gnu++11 -o main.o main.cpp
	g++ -o ./bin/GameOfLife_Shaders main.o -lsfml-graphics -lsfml-system -lsfml-window

# end
