##
# SFML compute shader learning
#
# @file
# @version 0.1
sfml-test: ./compute_shader.cpp
	g++ ./compute_shader.cpp -Wall -w -o ./bin/compshader-test -lsfml-graphics -lsfml-window -lsfml-system
# end
